jobs:
- name: jsoncleanerline_job
  plan:
  - get: jsoncleaner_repo_dockerfile
    trigger: true
  - put: jsoncleaner_build_image
    params: {build: jsoncleaner_repo_dockerfile}

resources:
- name: jsoncleaner_repo_dockerfile
  type: git
  source:
   uri: https://github.com/HedleyWard/Agile_Assignment.git
   branch: concourse
   paths: .

- name: jsoncleaner_build_image
  type: docker-image
  source:
    repository: yawlhead91/agile_concourse_test
    email: {{docker_mail}}
    username: {{docker_user}}
    password: {{docker_pass}}
